#!/usr/bin/env bash

set -euo pipefail # Bash 'strict mode'
export TERM=xterm-256color

tput setaf 3 # set text colour
echo '
      (¯`·¯`·.¸¸.··´¯)
      ( \          / )
       ( ) Kirill ( )
        (/        \)
         (.·´¯`·.¸) '

tput setaf 36
echo ''
echo 'Installing backend dependencies.'
echo '================================'
tput sgr0 # reset text colour
gem install rspec
bundle install

tput setaf 36
echo ''
echo 'Running backend tests.'
echo '======================='
tput sgr0
bundle exec rspec

tput setaf 36
echo ''
echo 'Installing frontend dependencies.'
echo '================================='
tput sgr0
npm i

tput setaf 36
echo ''
echo 'Running frontend tests.'
echo '======================='
tput sgr0
npm test

tput setaf 36
echo ''
echo 'Build frontend JavaScript bundle.'
echo '================================='
tput sgr0
npx parcel build --dist-dir public/js js/src/app.js